services:
  db:
    image: postgres:17-alpine
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: medods
    ports:
      - "54321:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: medods
      POSTGRES_HOST: db
    depends_on:
      - db

volumes:
  postgres_data: